#cloud-config
groups:
  - kofe

users:
  - default
  - name: kofe
    gecos: kofe
    shell: /bin/bash
    primary_group: kofe
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      ${ssh-public-key}
#      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB+ckmsfy6YoRqrXKjmJx2s7MO9n+iq6OUDCUi3DiiRz kofe

runcmd:
  - apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
  - sed -i 's/#Port 22/Port 2222/g' /etc/ssh/sshd_config
  - sed -i 's///g' sed -i 's/#PermitRootLogin No/PermitRootLogin No/g' /etc/ssh/sshd_config
  - sed -i 's/ENABLED=1/ENABLED=0/g' /etc/default/motd-news
  - sed -i 's/session    optional     pam_motd.so \(.*\)$/#session    optional     pam_motd.so \1/g' /etc/pam.d/sshd
  - touch /etc/motd
  - reboot
