---
- name: Set up test web server
  hosts: all
  tasks:
    - name: Do root works
      block:
        - name: Wait for cloud-inint complition
          ansible.builtin.script: "{{ wait_script }}"

        - name: Update apt-get repo and cache
          ansible.builtin.apt:
            update_cache=yes force_apt_get=yes cache_valid_time=3600

        - name: Install packages
          ansible.builtin.apt:
            pkg:
              - curl
              - git
              - apt-transport-https
              - ca-certificates
      when: ansible_facts['distribution'] == 'Ubuntu'
      become: true
      become_method: sudo
      become_user: root

    - name: Nginx
      hosts: all
      tasks:
        - name: Install NGINX
          ansible.builtin.include_role:
            name: nginxinc.nginx
          vars:
            nginx_branch: stable